# Cosmonic Control WorkloadDeployment for the SAR processor for dark-vessels.
apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: dv-sarproc
  namespace: cosmonic-system
spec:
  replicas: 1
  template:
    spec:
      hostInterfaces:
        - namespace: wasi
          package: logging
          version: 0.1.0-draft
          interfaces:
            - logging
        - namespace: wasi
          package: webgpu
          version: 0.0.1
          interfaces:
            - webgpu
        - namespace: wasmcloud
          package: messaging
          version: "0.2.0"
          interfaces:
            - handler
            - consumer
            - types
          config:
            subscriptions: tasks.sar-processor
      components:
        - name: sar-processor
          image: ghcr.io/cosmonic-labs/dark-vessels/sar-processor:0.1.0
          poolSize: 1
