package darkvessel:dark-vessels;

world api-gateway {
  import wasmcloud:messaging/consumer@0.2.0;
}

world sar-processor {
  import wasi:webgpu/webgpu@0.0.1;
  import wasmcloud:messaging/consumer@0.2.0;
  export wasmcloud:messaging/handler@0.2.0;
}
